repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args: [--args=--lockfile=false]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.0
    hooks:
      - id: check-github-actions
