- name: "Setup server"
  hosts: all
  become: yes
  become_user: root

  vars:
    new_username: "deploy"
    new_user_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOijXoLNkvJxCzAR3dgTi0gUl31To6ctGZjP03+ul/lX"

  tasks:
    - name: "Install sudo"
      apt:
        name: sudo
        state: present
      when: ansible_os_family == 'Debian'

    - name: "Create user {{ new_username }}"
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        groups: "sudo"
        append: yes
        generate_ssh_key: no

    - name: "Create .ssh directory"
      file:
        path: "/home/{{ new_username }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ new_username }}"
        group: "{{ new_username }}"

    - name: "Add SSH key to authorized_keys"
      ansible.posix.authorized_key:
        user: "{{ new_username }}"
        state: present
        key: "{{ new_user_ssh_key }}"
