- name: Setup nginx
  hosts: all
  become: yes
  become_user: root
  remote_user: root

  vars:
    nginx_user: www-data
    server_name: "default"
    web_root: "/var/www"
    repo_root: "/opt/startbootstrap-clean-blog"
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Stop Nginx (before config changes)
      service:
        name: nginx
        state: stopped

    - name: Configure main nginx.conf
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart Nginx

    - name: Configure site
      template:
        src: templates/site.conf.j2
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
        owner: root
        group: root
        mode: 0644
      notify: Restart Nginx

    - name: Install git
      apt:
        name: git
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/StartBootstrap/startbootstrap-clean-blog.git
        dest: "{{ repo_root }}"
        version: "master"
        clone: yes
        update: yes

    - name: Create web root directory
      file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: 0755

    - name: Remove default nginx configuration
      file:
        path: "{{ web_root }}/html"
        state: absent

    - name: Link site
      file:
        src: "{{ repo_root }}/dist"
        dest: "{{ web_root }}/html"
        state: link
      when: ansible_os_family == 'Debian'
      notify: Restart Nginx

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

