- name: Setup nginx
  hosts: all
  become: true
  become_user: root
  remote_user: root

  vars:
    nginx_user: www-data
    server_name: "default"
    web_root: "/var/www"
    repo_root: "/opt/startbootstrap-clean-blog"

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Stop Nginx (before config changes)
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Configure main nginx.conf
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Nginx

    - name: Configure site
      ansible.builtin.template:
        src: templates/site.conf.j2
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Restart Nginx

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/StartBootstrap/startbootstrap-clean-blog.git
        dest: "{{ repo_root }}"
        version: "master"
        clone: true
        update: true

    - name: Create web root directory
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: "0755"

    - name: Remove default nginx configuration
      ansible.builtin.file:
        path: "{{ web_root }}/html"
        state: absent

    - name: Link site
      ansible.builtin.file:
        src: "{{ repo_root }}/dist"
        dest: "{{ web_root }}/html"
        state: link
      when: ansible_os_family == 'Debian'
      notify: Restart Nginx

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
