name: Deploy Infrastructure
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Terraform Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          echo "${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
          TF_VAR_do_token: ${{ secrets.TF_VAR_DO_TOKEN }}
          TF_VAR_pvt_key: ~/.ssh/id_rsa
          TF_VAR_pub_key: ~/.ssh/id_rsa.pub
